import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:iconsax/iconsax.dart';

class AppIcons {
  static IconData get arrowBack => CupertinoIcons.back;
  static IconData get arrowForwardIos => Icons.keyboard_arrow_right_rounded;
  static IconData get homeOl => Iconsax.home_1;
  static IconData get home => Iconsax.home5;
  static IconData get addOl => Icons.add;
  static IconData get add => Iconsax.add_square5;
  static IconData get messageOl => Iconsax.message4;
  static IconData get message => Iconsax.message5;
  static IconData get settings => Icons.settings;
  static IconData get settingsOl => Iconsax.setting_2;
  static IconData get gallery => Iconsax.gallery;
  static IconData get order => Iconsax.shopping_cart5;
  static IconData get orderOl => Iconsax.shopping_cart;
  static IconData get delete => Iconsax.trash;
  static IconData get edit => Iconsax.edit;
  static IconData get user => Icons.person;
  static IconData get userOl => Iconsax.user;
  static IconData get users => Iconsax.people;
  static IconData get share => CupertinoIcons.share;
  static IconData get notifications => Iconsax.notification5;
  static IconData get notificationsOl => Iconsax.notification;
  static IconData get privacy => Icons.lock;
  static IconData get rate => Iconsax.star;
  static IconData get link => Iconsax.link_1;
  static IconData get send => Icons.send_outlined;
  static IconData get login => Iconsax.login;
  static IconData get logout => Icons.logout;
  static IconData get more => Icons.more_vert_rounded;
  static IconData get info => Iconsax.info_circle;
  static IconData get search => Iconsax.search_normal_14;
  static IconData get school => Icons.school;
  static IconData get hostel => Icons.business;
  static IconData get transaction => Icons.data_usage_rounded;
  static IconData get transactionOl => Icons.data_usage_outlined;
  static IconData get location => Iconsax.location;
  static IconData get star => CupertinoIcons.star_fill;
  static IconData get article => Icons.article;
  static IconData get articleOl => Icons.article_outlined;
  static IconData get filter => Icons.filter_list;
}
